### ISSUE TITLE
IO - 1/2/3 Hi/Lo status not shown on Triggers/IO screen

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-gui-2#38]
The C++ GUI shows whether IO 1, 2 and 3 are Hi or Lo any time the Trigger/IO screen is open, but GUI2 does not.

**Comment by sanjpm** [comment]
Implemented by https://github.com/krontech/chronos-gui-2/commit/e1e9e33ebb795b34f998ff02a01b24e1f9be6b17
