### ISSUE TITLE
chronos 2.1 - 1920x1080 not showing up in the resolution list

### ISSUE THREAD

**Issue by skronstein** [krontech/chronos-gui-2#72]
Sometimes, 1920x1080 would not be listed in the common resolutions dropdown.  In one case, I manually entered 1920 and 1080 for width and height and hit Done. After returning to the main screen, the image looked glitchy.  I don't remember in exactly what way.

**Comment by sanjpm** [comment]
Closed by https://github.com/krontech/chronos-gui-2/commit/a90fa09321852b5302d8591fca9b33d2fb678eaa
